#define VIAL_KEYBOARD_UID {0xB7, 0x83, 0xB5, 0xA0, 0x9D, 0x61, 0xE7, 0xD3}

#define VIAL_UNLOCK_COMBO_ROWS { 5, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 7 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8
