#define VIAL_KEYBOARD_UID {0x55, 0x61, 0x2C, 0xCD, 0xC4, 0xE0, 0x7C, 0x0C}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 3  }
#define VIAL_UNLOCK_COMBO_COLS { 0, 12 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8
