#define VIAL_KEYBOARD_UID {0x2E, 0x5B, 0x25, 0xCB, 0x89, 0x1E, 0xEA, 0x40}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 4 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
#define VIAL_COMBO_ENTRIES 12
#define VIAL_TAP_DANCE_ENTRIES 12
