#define VIAL_KEYBOARD_UID {0x8A, 0x58, 0x53, 0xD2, 0x28, 0x4B, 0xD8, 0x5E}

#define VIAL_UNLOCK_COMBO_ROWS { 1, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 2 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define LAYER_STATE_8BIT

#define STARTUP_SONG SONG(PREONIC_SOUND)
//#define STARTUP_SONG SONG(ZELDA_PUZZLE)
//#define STARTUP_SONG SONG(ZELDA_TREASURE)
//#define STARTUP_SONG SONG(MARIO_GAMEOVER)
//#define STARTUP_SONG SONG(IMPERIAL_MARCH)
//#define STARTUP_SONG SONG(ODE_TO_JOY)
