#define VIAL_KEYBOARD_UID {0x2B, 0xF8, 0x4A, 0x8F, 0x2B, 0xD3, 0x91, 0xA8}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 3  }
#define VIAL_UNLOCK_COMBO_COLS { 0, 12 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8
