#define VIAL_KEYBOARD_UID {0x6A, 0xE2, 0x22, 0xE1, 0x30, 0x39, 0xF9, 0x1B}

#define VIAL_UNLOCK_COMBO_ROWS { 3, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 6 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8
