#define VIAL_KEYBOARD_UID {0x7D, 0xD2, 0x6F, 0xF8, 0xAD, 0xA9, 0xEE, 0x99}

// #define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
// #define VIAL_UNLOCK_COMBO_COLS { 0, 11 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8
