#define VIAL_KEYBOARD_UID {0x61, 0x6A, 0xE0, 0x65, 0x45, 0x04, 0x11, 0xD3}

#define VIAL_UNLOCK_COMBO_ROWS { 1,  1  }
#define VIAL_UNLOCK_COMBO_COLS { 11, 12 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8

#undef RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_LIMIT_VAL 64

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_RETAIN_VAL
