#define VIAL_KEYBOARD_UID {0xB4, 0xAA, 0x39, 0xCB, 0x4A, 0xDF, 0xD3, 0xB7}

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8
