#define VIAL_KEYBOARD_UID {0xA6, 0x7F, 0x9D, 0x1F, 0xD8, 0x46, 0x30, 0x5C}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 4  }
#define VIAL_UNLOCK_COMBO_COLS { 0, 11 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8
